# Generated by Django 2.0.2 on 2018-02-14 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tovar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('scoro', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('title', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='tovar',
            name='article',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='tovar',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tovar.Group'),
        ),
        migrations.AddField(
            model_name='tovar',
            name='tags',
            field=models.ManyToManyField(to='tovar.Tag'),
        ),
        migrations.RunSQL(
            sql = 'alter table tovar_tovar alter column quantity set default 0 ;' ,
            reverse_sql = 'alter table tovar_tovar alter column quantity drop default ;'
        )
    ]
